// "use strict";

console.log("ok");
const mapInteractive = (countries) => {
	const events = ['mouseover', 'mouseout', 'click'];
	const colors = ['white', '#34365F', 'yellow'];

	for (let country of countries) {
		country = document.getElementById(country);

		if (!country)
			continue;

		for (let i = 0; i < events.length; i++){
			country.addEventListener(events[i], () => {
				if (country.children.length > 0)
					for (const land of country.children){
						land.style.fill = colors[i];
					}
				else
					country.style.fill = colors[i];
					console.log(country.id);
			});
		}
	}
}

mapInteractive([
  "australia",
  "colombia",
  "brasil",
  "venezuela",
  "ecuador",
  "peru",
  "bolivia",
  "paraguay",
  "chile",
  "uruguay",
  "argentina",
  "guyana",
  "surinam",
  "guyanaFrancesa",
  "panama",
  "elSalvador",
  "costaRica",
  "nicaragua",
  "honduras",
  "guatemala",
  "belice",
  "mexico",
  "cuba",
  "haiti",
  "jamaica",
  "republicaDominicana",
  "puertoRico",
  "estadosUnidos",
  "canada",
  "groenlandia",
  "islandia",
  "portugal",
  "españa",
  "francia",
  "reinoUnido",
  "irlanda",
  "belgica",
  "paisesBajos",
  "alemania",
  "dinamarca",
  "suiza",
  "italia",
  "austria",
  "republicaCheca",
  "polonia",
  "eslovaquia",
  "hungria",
  "eslovenia",
  "croacia",
  "bosniaYHerzegovina",
  "albania",
  "macedonia",
  "grecia",
  "bulgaria",
  "serbia",
  "montenegro",
  "rumania",
  "moldavia",
  "turquia",
  "ucrania",
  "bielorusia",
  "estonia",
  "letonia",
  "lituania",
  "finlandia",
  "noruega",
  "suecia",
  "rusia",
  "chipre",
  "siria",
  "libano",
  "armenia",
  "azerbaiyan",
  "iran",
  "irak",
  "afganistan",
  "turkmenistan",
  "tayikistan",
  "pakistan",
  "uzbekistan",
  "kazajistan",
  "kirguistan",
  "india",
  "nepal",
  "bangladesh",
  "butan",
  "china",
  "mongolia",
  "coreaDelNorte",
  "coreaDelSur",
  "japon",
  "birmania",
  "tailandia",
  "laos",
  "camboya",
  "vietnam",
  "sriLanka",
  "malasia",
  "indonesia",
  "papuaNuevaGuinea",
  "filipinas",
  "nuevaZelanda",
  "vanuatu",
  "timorOriental",
  "jordania",
  "israel",
  "arabiaSaudita",
  "kuwait",
  "emiratosArabesUnidos",
  "yemen",
  "oman",
  "egipto",
  "libia",
  "tunez",
  "argelia",
  "marruecos",
  "saharaOccidental",
  "mauritania",
  "senegal",
  "mali",
  "niger",
  "chad",
  "sudan",
  "eritrea",
  "etiopia",
  "yibuti",
  "somalia",
  "kenia",
  "uganda",
  "tanzania",
  "burundi",
  "ruanda",
  "republicaDemocraticaDelCongo",
  "republicaCentroAfricana",
  "camerun",
  "nigeria",
  "benin",
  "togo",
  "ghana",
  "costaDeMarfil",
  "burkinaFaso",
  "liberia",
  "sierraLeona",
  "guinea",
  "guineaBisau",
  "guineaEcuatorial",
  "gabon",
  "congo",
  "angola",
  "zambia",
  "zimbabue",
  "mozambique",
  "botsuana",
  "namibia",
  "sudafrica",
  "lesoto",
  "malaui",
  "madagascar"
]);
